version: "3.9"

services:
  db:
    image: postgres:15
    container_name: azure-todo-db
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: azure-todo-backend
    env_file:
      - backend/.env.docker
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: azure-todo-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres-data:
  frontend-node-modules:
